# test-yolo:
# 	modal serve /Users/liammckenna/vit-ai/api/vit-api/gpu_api/endpoints/yolo.py --timeout 500
# 	python3 test_yolo.py /Users/liammckenna/vit-ai/api/vit-api/tests/gpu_tests/assets/photos/149828.jpg
# test-clip:

# test-dino:
